### ISSUE TITLE
Reformat for Skyline-RS

### ISSUE THREAD

**Issue by FaultyPine** [rubendal/ssbu#5]
The goal of these changes is to allow Skyline-RS (a framework for ACMD and function hooking) to implement a macro that allows for copying code from the data viewer directly into a Smash project to make ACMD edits. 

To do this the following changes are needed:

hash40's around things that should have hash40's -- instead of
`Effect = collision_attr_normal` or `Bone = arml`   
it should be
`Effect = hash40("collision_attr_normal")` or `Bone = hash40("arml")`

Change hitbox labels with `/` in them to not have those... I.E. `Ground/Air` becomes `Ground_or_Air`

Make all booleans lowercase... `False` -> `false` and `True` -> `true`

**Comment by rubendal** [comment]
Made the changes to the script parser and added the updated scripts to the data viewer

* Hash40's are now printed as `hash40("[label]")`
* Removed `/` from Hitbox labels
* Booleans are all lowercase

![image](https://user-images.githubusercontent.com/10661132/85914165-922aa300-b800-11ea-8b52-34587f2eaecd.png)
